[package]
name = "weighted-probability-rs"
version = "0.1.0"
authors = ["Paul Freakn Baker <paul.nelson.baker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
fraction = "0.8.0"
